import { test } from 'node:test';
import assert from 'node:assert/strict';
import ts from 'typescript';
import { readFileSync, mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
const dir=mkdtempSync(join(tmpdir(),'wg-test-'));
const compile=s=>ts.transpileModule(s,{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;
writeFileSync(join(dir,'catalog.mjs'),compile(readFileSync('lib/catalog.ts','utf8')));
writeFileSync(join(dir,'route.mjs'),compile(readFileSync('app/api/checkout/route.ts','utf8').replace("@/lib/catalog","./catalog.mjs")));
const {POST}=await import(pathToFileURL(join(dir,'route.mjs')));
const {products,purchasable}=await import(pathToFileURL(join(dir,'catalog.mjs')));
const request=(body,origin='https://wronggoods.com')=>new Request('https://wronggoods.com/api/checkout',{method:'POST',headers:{origin,'Content-Type':'application/json'},body});
test('concept collections cannot reach checkout',async()=>{for(const p of products){assert.equal(purchasable(p),false);assert.equal((await POST(request(JSON.stringify({slug:p.slug})))).status,409)}});
test('foreign origins and malformed requests are rejected',async()=>{assert.equal((await POST(request('{}','https://evil.example'))).status,403);assert.equal((await POST(request('{'))).status,400);assert.equal((await POST(request('null'))).status,409)});
test('checkout requires an available product and an approved HTTPS provider',()=>{const p={...products[0],status:'available',priceGBP:24,checkoutUrl:'https://buy.stripe.com/test'};assert.equal(purchasable(p),true);for(const url of ['javascript:alert(1)','http://buy.stripe.com/test','https://buy.stripe.com.evil.example/test'])assert.equal(purchasable({...p,checkoutUrl:url}),false)});
test('published checkout ignores client-controlled URL and price',async()=>{const p=products[0];Object.assign(p,{status:'available',priceGBP:24,checkoutUrl:'https://buy.stripe.com/test'});try{const r=await POST(request(JSON.stringify({slug:p.slug,price:1,url:'https://evil.example'})));assert.equal(r.status,200);assert.deepEqual(await r.json(),{url:'https://buy.stripe.com/test'})}finally{Object.assign(p,{status:'in-development',priceGBP:null,checkoutUrl:null})}});
process.on('exit',()=>rmSync(dir,{recursive:true,force:true}));
