export const metadata={title:'Privacy'};
export default function Privacy(){return <main id="main" className="editorial-page legal-page">
  <header className="editorial-hero"><p className="eyebrow">PRIVACY / LAST UPDATED 19 SEPTEMBER 2026</p><h1>YOUR DETAILS.</h1><p>What we collect, why we collect it, and where it goes.</p></header>
  <section><h2>Release updates</h2><p>If you opt in, we store your email address, the consent wording and the time of signup so we can send WrongGoods release news. Signing up does not create a customer account.</p></section>
  <section><h2>Contact enquiries</h2><p>The contact form stores your name, email, message and submission time so WrongGoods can respond. Do not send payment-card details.</p></section>
  <section><h2>Checkout and downloads</h2><p>When products are released, Lemon Squeezy handles payment details, receipts, customer sign-in and secure file delivery. WrongGoods stores a limited order-status record and uses a short-lived HTTP-only checkout cookie to show verified payment status. Card information is never stored here.</p></section>
  <section><h2>Hosting and processors</h2><p>Cloudflare hosts the application. Supabase is used for private storefront data and owner administration where configured. Resend processes release-list addresses for email delivery. These providers may also process technical request information needed to operate and secure the service.</p></section>
  <section><h2>Your choices</h2><p>To unsubscribe, ask about stored information or request deletion where applicable, email <a className="text-link" href="mailto:hello@wronggoods.com">hello@wronggoods.com</a>. Release emails will include an unsubscribe option.</p></section>
  <section><h2>External services</h2><p>Instagram and Lemon Squeezy operate under their own privacy policies. No advertising trackers are enabled on the storefront.</p></section>
  <p className="legal-note">Seller details, retention periods and the final trading privacy notice must be confirmed before a paid launch.</p>
</main>}