'use client';
import Link from 'next/link';
import {useState} from 'react';
import {ArrowUpRight, Search, Menu, X} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetTrigger,SheetClose} from '@/components/ui/sheet';
import {products,categories,Product,purchasable} from '@/lib/catalog';
export function Header(){return <><div className="dispatch">INDEPENDENT FICTIONAL ASSET LABEL <span>FOR GAMES / FILM / INVENTED WORLDS</span></div><header className="header"><Link href="/" aria-label="WrongGoods home"><img className="logo" src="/brand/wordmark.svg" alt="WrongGoods" width="132" height="86"/></Link><nav aria-label="Main navigation"><Link href="/#goods">Browse goods</Link><Link href="/#departments">Departments</Link><Link href="/licence">Licensing</Link><Link href="/about">The label</Link></nav><Link className="header-action" href="/#goods" aria-label="Search goods"><Search size={20}/></Link><Sheet><SheetTrigger className="mobile-menu" aria-label="Open menu"><Menu/></SheetTrigger><SheetContent><SheetTitle>WrongGoods</SheetTitle><nav className="mobile-nav">{[['Browse goods','/#goods'],['Licensing','/licence'],['The label','/about']].map(([text,href])=><SheetClose asChild key={href}><Link href={href}>{text}</Link></SheetClose>)}</nav></SheetContent></Sheet></header></>}
export function Footer(){return <footer><div className="footer-top"><Link href="/" className="footer-name">WRONG GOODS™</Link><p>The wrong goods. In the right hands.</p></div><div className="footer-bottom"><span>© {new Date().getFullYear()} WrongGoods</span><Link href="/licence">Licensing</Link><Link href="/privacy">Privacy</Link><a href="mailto:tawseen@wronggoods.com">Contact ↗</a><a href="https://www.instagram.com/wronggoodsco/" target="_blank" rel="noopener noreferrer">Instagram ↗</a></div></footer>}
export function Catalogue(){const[category,setCategory]=useState('All goods');const[query,setQuery]=useState('');const filtered=products.filter(p=>(category==='All goods'||p.category===category)&&`${p.name} ${p.description} ${p.tone}`.toLowerCase().includes(query.toLowerCase()));return <section className="catalogue" id="goods"><div className="section-heading"><div><span className="eyebrow">THE RELEASE MANIFEST / 001—003</span><h2>GOODS IN THE MAKING.</h2></div><p>First collections. Currently on the workbench.</p></div><div className="catalogue-tools"><div className="filters" aria-label="Filter by department">{categories.map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><label className="search"><Search size={18}/><span className="sr-only">Search goods</span><input type="search" placeholder="Search goods" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><X size={16}/></button>}</label></div><p className="result-count" aria-live="polite">{filtered.length} {filtered.length===1?'collection':'collections'}</p><div className="product-grid">{filtered.map(p=><Link className="product" key={p.slug} href={`/goods/${p.slug}`}><div className={`product-art ${p.slug}`} >{p.image?<img src={p.image} alt="DAYSHIFT fictional coffee packaging concept" loading="lazy"/>:<div className="type-cover"><span>{p.code} / CONCEPT IN DEVELOPMENT</span><strong>{p.name.replace(' ','\n')}</strong><span>{p.category.toUpperCase()}</span></div>}<span className="status-tag">IN DEVELOPMENT</span></div><div className="product-meta"><span>{p.category} / {p.tone}</span><ArrowUpRight size={22}/></div><h3>{p.name}</h3><p>{p.description}</p><div className="product-bottom"><span>Release details to follow</span><span>View collection ↗</span></div></Link>)}</div>{!filtered.length&&<div className="empty"><h3>Nothing in this department.</h3><p>Try a different search or reset the filters.</p><button className="button" onClick={()=>{setQuery('');setCategory('All goods')}}>Reset filters</button></div>}</section>}
export function Purchase({product:p}:{product:Product}){const[error,setError]=useState('');const[busy,setBusy]=useState(false);async function checkout(){setBusy(true);setError('');try{const r=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slug:p.slug})});const data=await r.json() as {error?:string;url?:string};if(!r.ok)throw Error(data.error||'Checkout is unavailable.');if(!data.url)throw Error('Checkout is unavailable.');window.location.assign(data.url)}catch(e){setError(e instanceof Error?e.message:'Checkout is unavailable.');setBusy(false)}}return purchasable(p)?<div><p className="price">£{p.priceGBP?.toFixed(2)}</p><button className="button" disabled={busy} onClick={checkout}>{busy?'Opening checkout…':'Buy collection ↗'}</button>{error&&<p role="alert">{error}</p>}</div>:<div className="release-note"><strong>Currently in development.</strong><p>This is a collection preview. Final contents, formats, price and licence will be confirmed before release.</p><a className="button" href={`mailto:tawseen@wronggoods.com?subject=${encodeURIComponent(`Release enquiry: ${p.name}`)}`}>Ask about this release <ArrowUpRight size={18}/></a></div>}
