import {readFileSync,writeFileSync} from 'node:fs';
const path = new URL('../dist/server/wrangler.json',import.meta.url);
const config=JSON.parse(readFileSync(path,'utf8'));
const databaseId=process.env.WRONGGOODS_PREVIEW_DATABASE_ID;
const bucket=process.env.WRONGGOODS_PREVIEW_BUCKET;
if(databaseId&&!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(databaseId))throw Error('Use the actual Cloudflare preview database UUID.');
if(databaseId==='00000000-0000-4000-8000-000000000000')throw Error('The local placeholder database cannot be deployed.');
if(bucket&&!/^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$/.test(bucket))throw Error('Invalid private preview bucket name.');
config.name='wronggoods-preview';
config.topLevelName='wronggoods-preview';
config.workers_dev=true;
config.preview_urls=false;
config.routes=[];
config.d1_databases=databaseId?[{binding:'DB',database_name:'wronggoods-preview',database_id:databaseId,migrations_dir:'../../migrations'}]:[];
config.r2_buckets=bucket?[{binding:'BUCKET',bucket_name:bucket}]:[];
config.observability={enabled:false};
config.vars={COMMERCE_LIVE_ENABLED:'false'};
config.keep_vars=true;
writeFileSync(new URL('../dist/server/wrangler.preview.json',import.meta.url),JSON.stringify(config,null,2)+'\n');
console.log(`Prepared separate wronggoods-preview Worker; database ${databaseId?'bound':'disabled'}, private storage ${bucket?'bound':'disabled'}, live payments disabled, no domain routes.`);
