import './sites-env.mjs';
import {existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {spawn} from 'node:child_process';
const args=['node_modules/wrangler/bin/wrangler.js','dev','--config','dist/server/wrangler.json','--local','--persist-to','.wrangler/state','--ip','127.0.0.1','--inspector-port','0'];
if(existsSync('.dev.vars'))args.push('--env-file',resolve('.dev.vars'));
const child=spawn(process.execPath,args,{stdio:'inherit',windowsHide:true});
process.on('SIGINT',()=>child.kill('SIGINT'));
process.on('SIGTERM',()=>child.kill('SIGTERM'));
child.on('exit',code=>process.exit(code??1));
